### ISSUE TITLE
Snippetの依存ライブラリが指定できない

### ISSUE THREAD

**Issue by pm-twice** [hatoo/cargo-snippet#10]
例えばlockを用いた高速なScannerをスニペットに登録する際に、structそのものの登録は行えても、
スニペット貼り付けのたびに依存するライブラリである`std::io::Read, std::str::FromStr`などを記載する必要があり、少々手間がかかってしまいます。
アトリビュートにuse,libなどを追加してそのスニペットが依存しているライブラリ(もしくは単純に文字列でも)を登録可能にはできないでしょうか？

docアトリビュートとgrepの組み合わせで似たようなことができないか試しているのですが、rust-docのtest部分のuseと被って抽出が上手くいかないのです。

**Comment by hatoo** [comment]
#11 に実装してみました
```
cargo install --git=https://github.com/hatoo/cargo-snippet.git --branch="prefix" --features="binaries"
```
でインストールできるので試してもらって良さそうならマージします:+1:

**Comment by pm-twice** [comment]
対応ありがとうございます。早速試してみました。

`#[snippet(prefix = "use std::io;")]`が無事に出力されることも確認しました。

ただ、複数行のuseが存在する場合に、改行コードを入れるとエラーが出てしまうのは利用上の注意書きにあった方がいいかと思います。

初めに複数行出力を以下の2通りで試して`ERROR cargo_snippet::writer] rustfmt returns non-zero status`と表示されて戸惑ってしまったので。

```
#[snippet(prefix="use std::io::{self,Read};\nuse std::str::FromStr;")]
#[snippet(prefix=r"use std::io::{self,Read};
use std::str::FromStr;")]
```

`;`に対して自動で改行がなされることはReadmeあたりに書いておいた方がいいかもしれません。

```
#[snippet(prefix="use std::io::{self,Read};use std::str::FromStr;")]
```

あるいは、見た目上で2行に分けて利用しても問題ないとも。

```
#[snippet(prefix="use std::io::{self,Read};")]
#[snippet(prefix="use std::str::FromStr;")]
```

Rustをまだ学習中のため、的外れな指摘だったらすいません。

**Comment by hatoo** [comment]
ありがとうございます。

prefixに`\n`などのエスケープされた文字列が入っててもいいように修正しました。 #11 

> ;に対して自動で改行がなされることはReadmeあたりに書いておいた方がいいかもしれません。

これは出力の際にrustfmtがかかるので`use`が自動的に整形されているためです。
rustfmtがかかる理由は https://github.com/hatoo/cargo-snippet/issues/2#issuecomment-489545508

ドキュメントに後で書いておきます

**Comment by pm-twice** [comment]
ご対応ありがとうございます。
こちらでも無事、エスケープ文字入りでも出力されることが確認できました。

**Comment by hatoo** [comment]
マージしました。
何か問題がありましたらこのissueを再オープンしてください
