### ISSUE TITLE
The template is not included in the output 

### ISSUE THREAD

**Issue by akiradeveloper** [hatoo/cargo-snippet#12]
I found the template snippet is not included in the output. I've tested with your snippet repo. I hope you please retest and fix when you have time.

**Comment by hatoo** [comment]
Could you tell me about witch version of cargo-snippet used to extract snippet?

**Comment by akiradeveloper** [comment]
https://github.com/hatoo/competitive-rust-snippets  I've cloned your repo and run `cargo snippet` and there is no template in the output. The repo is using 0.4.

The first issue I found is when I am using my snippet repo https://github.com/akiradeveloper/rust-comp-snippets, which is using 0.5 that should be latest.

FYI, I am using rustc 1.43-beta. I am doing something wrong with this?

**Comment by akiradeveloper** [comment]
Now I am using 1.42 but could't see the template in it.

**Comment by hatoo** [comment]
A cargo-snippet version of Cargo.toml is irrelevant.
The matter is the version of cargo-snippet binary which typically installed by `cargo install cargo-snippet -- features="binaries"`.
You can see the binary version by `cargo snippet -V`.

Fortunately, I've created a web service that runs cargo-snippet on the specified repo. URL is https://cargo-snippet.hatoo.io/ which uses cargo-snippet 0.5
According to this, I've confirmed that template is printed.

https://cargo-snippet.hatoo.io/snippet?url=https://github.com/akiradeveloper/rust-comp-snippets&t=vscode
https://cargo-snippet.hatoo.io/snippet?url=https://github.com/hatoo/competitive-rust-snippets.git&t=vscode

**Comment by akiradeveloper** [comment]
Sorry to trouble you. Resolved.
