### ISSUE TITLE
VSCodeのスニペットでマクロの変数がプレースホルダーとして扱われる

### ISSUE THREAD

**Issue by u74w** [hatoo/cargo-snippet#19]
VSCodeでスニペットを呼び出す際，$aなどのマクロの変数がプレースホルダーとして扱われてしまい，$が消えてしまいます．
\\\\$aのように\\\\を前につけたところ，$aはそのまま出力されるようでした．
そのため，例えばVSCodeのスニペットを出力する際に，マクロの定義であれば$を\\\\$に変換するなどの修正を検討していただけないでしょうか．

**Comment by hatoo** [comment]
報告ありがとうございます
自分はVSCodeを使っていないので気づきませんでした 😓 

#20 に、`$`を`\\$`に置き換えるPRを出しました
```
cargo install --git=https://github.com/hatoo/cargo-snippet.git --branch="fix-vscode-placeholder" --features="b
inaries"
```
でインストールできます。

これで解決するならマージするのでそちらでも試していただけますか？
よろしくおねがいします

**Comment by u74w** [comment]
インストールしたら解決しました！
ご対応ありがとうございます:smiley:
