### ISSUE TITLE
CI fail

### ISSUE THREAD

**Issue by hatoo** [hatoo/cargo-snippet#23]
https://travis-ci.org/github/hatoo/cargo-snippet/builds/690050347

**Comment by magurotuna** [comment]
I'm working on this issue.

**Comment by magurotuna** [comment]
```rust
/** This is outer doc comment.
doc comment1
* doc comment2
 doc comment finishes here! */
/*
NOT doc comment
*/
/*** NOT doc comment */
#[snippet]
fn foo() {}
```

In `proc-macro2: 1.0.13`, the parse result of the above code looks like:


```
tokens: TokenStream [
    Punct {
        op: '=',
        spacing: Alone,
    },
    Literal {
        lit: "/** This is outer doc comment.\ndoc comment1\n* doc comment2\n doc comment finishes here! */",
    },
],
```

while in `1.0.14`, the result is:

```
tokens: TokenStream [
    Punct {
        op: '=',
        spacing: Alone,
    },
    Literal {
        lit: " This is outer doc comment.\ndoc comment1\n* doc comment2\n doc comment finishes here! ",
    },
],
```

**Comment by hatoo** [comment]
According to Semantic Versioning, `proc-macro2: 1.0.14` must-have backward compatibility to `1.0.13` I guess.
So please consider opening an issue to [proc-macro2](https://github.com/alexcrichton/proc-macro2) if you think it breaks backward compatibility and you have time.

**Comment by magurotuna** [comment]
Yeah, as you are saying, it breaks backward compatibility. I'll open an issue later.
Anyway, I'm going to try to fix `cargo-snippet` itself so as to work with proc-macro2 1.0.14+.
