### ISSUE TITLE
Feature request: hidden doc comments

### ISSUE THREAD

**Issue by magurotuna** [hatoo/cargo-snippet#28]
Currently, cargo-snippet's output includes doc comments in all cases.
This is surely a good feature for some users, but there may be other users who want doc comments to be removed from output because of verboseness.

Therefore, it would be nice if we introduce a new syntax like this:

```rust
/// many
/// doc
/// comments
#[snippet(doc_hidden)]
fn foo() {
    // omitted
}
```

and when `doc_hidden` is applied, cargo-snippet doesn't output doc comments.

What do you think about this @hatoo? If there's no problem, I'll implement it this weekend.

**Comment by hatoo** [comment]
Yeah, it's a good feature indeed.
Please implement it. 😄 
Thank you!
